# This workflow will build a Puppet Code Package and run tests
---
name: Puppet Code Continuous Integration

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: ["main"]

permissions:
    id-token: write  # This is required for requesting the JWT
    contents: read

env:
    ROLE_ARN: "arn:aws:iam::493370826424:role/ih-tf-puppet-code-github"

jobs:
    test:
        runs-on: ubuntu-24.04
        strategy:
            matrix:
                codename: ["noble"]
        steps:
            - uses: actions/checkout@v3
            - name: Install InfraHouse APT repository
              run: |
                sudo make install-infrahouse-repo
            - name: Install dependencies
              run: |
                sudo bash support/install_deps.sh

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  role-to-assume: ${{ env.ROLE_ARN }}
                  role-session-name: github-action-puppet-code-cd
                  aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

            - name: Build package
              run: |
                OS_VERSION=${{ matrix.codename }} make package
